[game]
# maximum altitude for drawing the background image (unit: m)
maxAltitude=100

[simulation]
# launch rod angle from vertical (unit: degrees)
launchRod.angle=90
# launch rod length (unit: m)
launchRod.length=1.5
# wind speed (unit: m/s)
windspeed=0


[openrocket]
# Download URL for OpenRocket
# If the jar file does not exist in the root directory, it will be downloaded from this URL
# Please refer to the orhelper documentation and select an appropriate version from the OpenRocket repository
# (see also: https://github.com/openrocket/openrocket/releases)
url="https://github.com/openrocket/openrocket/releases/download/release-23.09/OpenRocket-23.09.jar"

